### ISSUE TITLE
Cant update heroku url variable via url

### ISSUE THREAD

**Issue by milindpatel63** [urbanishimwe/roker#2]
I am having trouble when update my heroku url config var when my ngrok url changes...
it always says tunnel not found...
what heroku url should i be using to update?

**Comment by urbanishimwe** [comment]
@milindpatel63 does your fork fix the issue?

**Comment by milindpatel63** [comment]
@urbanishimwe there is nothing different in my fork...you can use the original project...i actually use a different way of updating url in heroku..

curl -n -X PATCH https://api.heroku.com/apps/ENTER_APP_NAME_HERE/config-vars   -d '{ "URL": "ENTER_URL_HERE" }'   -H "Content-Type: application/json"   -H "Accept: application/vnd.heroku+json; version=3"   -H "Authorization: Bearer ENTER_HEROKU_ACCOUNT_API_HERE"

use the above command in shell...
get heroku api from heroku website in account settings...
tested in ubuntu 20.04
